#!/bin/bash

echo " " 
echo "Vamos atualizar a porra do sistema!" 
echo " " 

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get full-upgrade -y && sudo apt-get autoremove -y && sudo apt-get autoclean && sudo apt-get clean && update-grub

sudo rm -R /var/log/* 

sudo mkdir /var/log/apt

echo " " 
echo "Terminou, disgraça!" 
echo " " 
echo "Vai carai!!!" 
echo " " 
