#!/bin/bash

echo " " 
echo "Vamos atualizar a porra do sistema!" 
echo " " 


echo " "
echo "Atualizaçao APT"
echo " "

sudo apt update; sudo apt upgrade -y; sudo apt dist-upgrade -y; sudo apt full-upgrade -y; sudo apt autoremove -y; sudo apt autoclean; sudo apt clean; sudo update-grub

sudo rm -R /var/log/* 

sudo mkdir /var/log/apt


echo " "
echo "Atualização Flatpak"
echo " "

flatpak update -y


echo " "
echo "Atualização PIP"
echo " "

pip3 install --upgrade pip


echo " "
echo "Atualizaçao R"
echo " "

Rscript -e 'update.packages(checkBuilt=TRUE,ask=FALSE,dependencies=TRUE,force=TRUE,repo="https://cran-r.c3sl.ufpr.br")'


echo " "
echo "Atualização conda base"
echo " "

conda update --all -y; conda update conda -y
echo " " 
echo "Terminou, disgraça!" 
echo " " 
echo "Vai carai!!!" 
echo " " 

exit
